services:
  nextjs:
    container_name: nextjs
    image: safehomejdev/nextjs-k3s:dev
    build:
      context: ../nextjs
      dockerfile: ../nextjs/docker/Dockerfile
      args:
        - MONGODB_USERNAME=${MONGODB_USERNAME}
        - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - 3000:3000
    environment:
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
  db:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
