apiVersion: v1
kind: Namespace
metadata:
  name: nextjs-k3s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-k3s
  labels:
    app: nextjs-k3s
  namespace: nextjs-k3s
spec:
  selector:
    matchLabels:
      app: nextjs-k3s
  template:
    metadata:
      labels:
        app: nextjs-k3s
      namespace: nextjs-k3s
    spec:
      containers:
        - imagePullPolicy: Always
          name: nextjs
          image: safehomejdev/nextjs-k3s:latest
          envFrom:
            - secretRef:
                name: nextjs-k3s-secrets
                optional: false
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              port: 3000
              path: /api/healthz
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 0
            timeoutSeconds: 1
            periodSeconds: 10
            httpGet:
              scheme: HTTP
              port: 3000
              path: /api/healthz
          resources:
            requests:
              cpu: 125m
              memory: 128Mi
            limits:
              cpu: 125m
              memory: 128Mi
        - imagePullPolicy: Always
          name: mongodb
          image: mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGODB_USERNAME
                  name: nextjs-k3s-secrets
                  optional: false
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGODB_PASSWORD
                  name: nextjs-k3s-secrets
                  optional: false
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: MONGODB_DATABASE
                  name: nextjs-k3s-secrets
                  optional: false
          ports:
            - containerPort: 27017
              name: mongo
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 45
            timeoutSeconds: 5
            periodSeconds: 10
            exec:
              command:
                - mongosh
                - "--version"
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 45
            timeoutSeconds: 5
            periodSeconds: 10
            exec:
              command:
                - mongosh
                - "--version"
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
      restartPolicy: Always
  replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: nextjs-k3s-secrets
  namespace: nextjs-k3s
type: Opaque
data:
  MONGODB_DATABASE: dGVzdA==
  MONGODB_HOSTNAME: bmV4dGpzLWszcw==
  MONGODB_PASSWORD: bW9uZ29fYWRtaW4=
  MONGODB_PORT: MjcwMTc=
  MONGODB_USERNAME: YWRtaW4=
  SERVER_URL: aHR0cHM6Ly9uZXh0anMtazNzLnNhZmVob21lZGV2LmNvbQ==